#ifndef __SERVERS_H__
#define __SERVERS_H__

#define CLOCK_SERVER            "CLOCK_SERVER"
#define RAND_SERVER             "RAND_SERVER"
#define RPS_SERVER              "RPS_SERVER"
#define UART1_RECEIVE_SERVER    "UART1_RECEIVE_SVR"
#define UART1_TRANSMIT_SERVER   "UART1_TRANSMIT_SVR"
#define UART2_RECEIVE_SERVER    "UART2_RECEIVE_SVR"
#define UART2_TRANSMIT_SERVER   "UART2_TRANSMIT_SVR"
#endif
