#ifndef __SERVERS_H__
#define __SERVERS_H__

#define CLOCK_SERVER               "CLOCK_SERVER"
#define RAND_SERVER                "RAND_SERVER"
#define RPS_SERVER                 "RPS_SERVER"
#define IDLE_TASK_ID             4

#define UART1_RECEIVE_SERVER       "UART1_RECEIVE_SVR"
#define UART1_RECEIVE_SERVER_ID    5
#define UART1_TRANSMIT_SERVER      "UART1_TRANSMIT_SVR"
#define UART1_TRANSMIT_SERVER_ID   6
#define UART2_RECEIVE_SERVER       "UART2_RECEIVE_SVR"
#define UART2_RECEIVE_SERVER_ID    7
#define UART2_TRANSMIT_SERVER      "UART2_TRANSMIT_SVR"
#define UART2_TRANSMIT_SERVER_ID   8
#define UART2_COURRIER             "UART2_COURRIER"

#define COMMAND_SERVER_ID		   9
#define COMMAND_SERVER 			   "COMMAND_SERVER"

#define TERMINAL_SERVER            "TERMINAL_SERVER"
#define TERMINAL_SERVER_ID         10

#define TRAIN_CONTROLLER_SERVER    "TRAIN_CTRL_SERVER"
#define TRAIN_CONTROLLER_SERVER_ID 11
#endif
