#ifndef _TASK_PRIORITIES_H_
#define _TASK_PRIORITIES_H_
#include <common.h>


#define TASK_HIGHEST_PRIORITY      31
#define TASK_LOWEST_PRIORITY       0

// Tasks created by kernel
#define NAME_SERVER_PRIORITY 			TASK_HIGHEST_PRIORITY
#define FIRST_USER_TASK_PRIORITY		TASK_HIGHEST_PRIORITY
#define IDLE_TASK_PRIORITY				TASK_LOWEST_PRIORITY
#define CLOCK_SERVER_PRIORITY			TASK_HIGHEST_PRIORITY - 1
#define RAND_SERVER_PRIORITY			TASK_HIGHEST_PRIORITY - 1
#define UART1_RECEIVE_SERVER_PRIORITY	TASK_HIGHEST_PRIORITY - 1
#define UART1_TRANSMIT_SERVER_PRIORITY	TASK_HIGHEST_PRIORITY - 1
#define UART2_RECEIVE_SERVER_PRIORITY	TASK_HIGHEST_PRIORITY - 1
#define UART2_TRANSMIT_SERVER_PRIORITY	TASK_HIGHEST_PRIORITY - 1
#define COMMAND_SERVER_PRIORITY			TASK_HIGHEST_PRIORITY - 3
#define TRAIN_CONTROLLER_COMMAND_SERVER	TASK_HIGHEST_PRIORITY - 2
#define TERMINAL_SERVER_PRIORITY		TASK_HIGHEST_PRIORITY - 3


//Tasks created in user space
#define CLOCK_NOTIFIER_TASK_PRIORITY	TASK_HIGHEST_PRIORITY
#define UART1_TRANSMIT_NOTIFIER_PRIORITY TASK_HIGHEST_PRIORITY - 1
#define UART1_RECEIVE_NOTIFIER_PRIORITY TASK_HIGHEST_PRIORITY - 1
#define UART2_TRANSMIT_NOTIFIER_PRIORITY TASK_HIGHEST_PRIORITY - 1
#define UART2_RECEIVE_NOTIFIER_PRIORITY TASK_HIGHEST_PRIORITY - 1
#define UART_COURRIER_PRIORITY			TASK_HIGHEST_PRIORITY - 1
#define UART2_TIMEOUT_NOTIFIER_PRIORITY TASK_HIGHEST_PRIORITY - 1
#define SENSOR_QUERY_SERVER_PRIORITY	TASK_HIGHEST_PRIORITY - 1
#define TRAIN_REVERSE_DELAY_SERVER_PRIORITY	TASK_HIGHEST_PRIORITY - 1
#define TERMINAL_TICK_NOTIFIER_PRIORITY		TASK_HIGHEST_PRIORITY - 1
#define TRAIN_POSITION_SERVER_PRIORITY		 TASK_HIGHEST_PRIORITY - 3

#define TRAIN_SERVER_PRIORITY 				TASK_HIGHEST_PRIORITY - 4

#endif //_TASK_PRIORITIES_H_
